src/java/at/htlpinkafeld/htlplusinformatik/dto/Bildungspartner.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package at.htlpinkafeld.htlplusinformatik.dto;

import java.util.Objects;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;

/**
 *
 * @author Andor
 */
public class Bildungspartner implements Identifiable {
    public static Logger logger = Logger.getLogger(Bildungspartner.class);
    
    private int num;
    private String firma;
    //private String ansprPers;
    private String addr;
    private String plz;
    private String ort;
    private boolean isAbsolvent;
    private String website;
    private String fax = "kein Fax";
    private String email;
    //private String tel;
    private boolean isBezahlt;
    private int betrag = 0;
    private String anmerk = " - ";
    private String eDatum = " - ";
    private String aDatum = " - ";

    public Bildungspartner() {
        this.num = -1;
        logger.log(Level.DEBUG, "Created empty Bildungspartner");
    }

    public Bildungspartner(String firma, String addr, String plz, String ort, boolean isAbsolvent, String website, String fax, String email, int betrag, boolean isBezahlt, String anm, String eDat, String aDat) {
        this();
        this.firma = firma;
        //this.ansprPers = ansprPers;
        this.addr = addr;
        this.plz = plz;
        this.ort = ort;
        this.isAbsolvent = isAbsolvent;
        this.website = website;
        this.fax = fax;
        this.email = email;
        this.anmerk = anm;
        this.eDatum = eDat;
        this.aDatum = aDat;
        this.isBezahlt = isBezahlt;
        this.betrag = betrag;
        logger.log(Level.DEBUG, "Created Bildungspartner");
    }

    @Override
    public int getId() {
        return this.num;
    }

    @Override
    public void setId(int id) {
        this.num = id;
    }

    public int getNum() {
        return num;
    }

    public void setNum(int num) {
        this.num = num;
    }

    public String getFirma() {
        return firma;
    }

    public void setFirma(String firma) {
        this.firma = firma;
    }
    
    

    /*public String getAnsprPers() {
        return ansprPers;
    }

    public void setAnsprPers(String ansprPers) {
        this.ansprPers = ansprPers;
    }*/

    public String getAddr() {
        return addr;
    }

    public void setAddr(String addr) {
        this.addr = addr;
    }

    public String getPlz() {
        return plz;
    }

    public void setPlz(String plz) {
        this.plz = plz;
    }

    public String getOrt() {
        return ort;
    }

    public void setOrt(String ort) {
        this.ort = ort;
    }

    public boolean isAbsolvent() {
        return isAbsolvent;
    }

    public void setAbsolvent(boolean isAbsolvent) {
        this.isAbsolvent = isAbsolvent;
    }

    public String getWebsite() {
        return website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    public String getFax() {
        return fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    
    
    public boolean isBezahlt() {
        return isBezahlt;
    }

    public void setBezahlt(boolean isBezahlt) {
        this.isBezahlt = isBezahlt;
    }

    public int getBetrag() {
        return betrag;
    }

    public void setBetrag(int betrag) {
        this.betrag = betrag;
    }

    public String getAnmerk() {
        return anmerk;
    }

    public void setAnmerk(String anmerk) {
        this.anmerk = anmerk;
    }

    public boolean isIsAbsolvent() {
        return isAbsolvent;
    }

    public void setIsAbsolvent(boolean isAbsolvent) {
        this.isAbsolvent = isAbsolvent;
    }

    public String geteDatum() {
        return eDatum;
    }

    public void seteDatum(String eDatum) {
        this.eDatum = eDatum;
    }

    public String getaDatum() {
        return aDatum;
    }

    public void setaDatum(String aDatum) {
        this.aDatum = aDatum;
    }

    

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + this.num;
        hash = 97 * hash + Objects.hashCode(this.firma);
        hash = 97 * hash + Objects.hashCode(this.addr);
        hash = 97 * hash + Objects.hashCode(this.plz);
        hash = 97 * hash + Objects.hashCode(this.ort);
        hash = 97 * hash + (this.isAbsolvent ? 1 : 0);
        hash = 97 * hash + Objects.hashCode(this.website);
        hash = 97 * hash + Objects.hashCode(this.fax);
        hash = 97 * hash + Objects.hashCode(this.anmerk);
        hash = 97 * hash + Objects.hashCode(this.eDatum);
        hash = 97 * hash + Objects.hashCode(this.aDatum);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Bildungspartner other = (Bildungspartner) obj;
        if (this.num != other.num) {
            return false;
        }
        if (this.isAbsolvent != other.isAbsolvent) {
            return false;
        }
        if (!Objects.equals(this.firma, other.firma)) {
            return false;
        }
        if (!Objects.equals(this.addr, other.addr)) {
            return false;
        }
        if (!Objects.equals(this.plz, other.plz)) {
            return false;
        }
        if (!Objects.equals(this.ort, other.ort)) {
            return false;
        }
        if (!Objects.equals(this.website, other.website)) {
            return false;
        }
        if (!Objects.equals(this.fax, other.fax)) {
            return false;
        }
        if (!Objects.equals(this.anmerk, other.anmerk)) {
            return false;
        }
        if (!Objects.equals(this.eDatum, other.eDatum)) {
            return false;
        }
        if (!Objects.equals(this.aDatum, other.aDatum)) {
            return false;
        }
        return true;
    }

    

    @Override
    public String toString() {
        return "Bildungspartner{" + "num=" + num + ", firma=" + firma + ", addr=" + addr + ", plz=" + plz + ", ort=" + ort + ", isAbsolvent=" + isAbsolvent + ", website=" + website + ", fax=" + fax + ", anmerk=" + anmerk + ", eDatum=" + eDatum + ", aDatum=" + aDatum + '}';
    }
    
            
}

src/java/at/htlpinkafeld/htlplusinformatik/presentation/LoginBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package at.htlpinkafeld.htlplusinformatik.presentation;

import at.htlpinkafeld.htlplusinformatik.dto.Benutzer;
import at.htlpinkafeld.htlplusinformatik.dto.Benutzer.Right;
import at.htlpinkafeld.htlplusinformatik.service.HtlPlusService;
import at.htlpinkafeld.htlplusinformatik.utils.PasswordUtils;
import java.io.IOException;
import java.io.Serializable;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;

/**
 *
 * @author Daniel Altmann
 */
@ManagedBean(name = "loginBean")
@SessionScoped
public class LoginBean implements Serializable {

    private static Logger logger = Logger.getLogger(LoginBean.class);

    private HtlPlusService service = new HtlPlusService();

    private String username;
    private String password;
    private Right right;

    private String chechPw;
    private String newPw;
    private String newPw1;

    public LoginBean() {
        logger.log(Level.DEBUG, "Created instance of LoginBean.");
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getChechPw() {
        return chechPw;
    }

    public void setChechPw(String chechPw) {
        this.chechPw = chechPw;
    }

    public String getNewPw() {
        return newPw;
    }

    public void setNewPw(String newPw) {
        this.newPw = newPw;
    }

    public String getNewPw1() {
        return newPw1;
    }

    public void setNewPw1(String newPw1) {
        this.newPw1 = newPw1;
    }

    public void login() throws IOException {
        FacesContext context = FacesContext.getCurrentInstance();
        FacesMessage message = null;

        Benutzer b = null;

        b = service.selectBenutzer(username);

        String salt = null;
        String providedPassword = null;
        String securePassword = null;

        if (b != null) {
            salt = b.getSalt();
            providedPassword = this.password;
            securePassword = b.getPassword();
        }

        boolean passwordsMatch = PasswordUtils.verifyUserPassword(providedPassword, securePassword, salt);

        if (passwordsMatch) {
            if (b.getRight() == Right.ADMIN) {
                this.right = Right.ADMIN;
                message = new FacesMessage(FacesMessage.SEVERITY_INFO, "Welcome", username);

                context.getExternalContext().redirect("/HTL_Plus_Informatik/faces/restricted/AdminStart.xhtml");
                context.getExternalContext().getFlash().setKeepMessages(true);

                HttpSession session = (HttpSession) context.getExternalContext().getSession(true);
                session.setAttribute("loggedIn", new Object());
            } else {
                this.right = Right.USER;
                message = new FacesMessage(FacesMessage.SEVERITY_INFO, "Welcome", username);

                context.getExternalContext().redirect("/HTL_Plus_Informatik/faces/MitgliedStart.xhtml");
                context.getExternalContext().getFlash().setKeepMessages(true);

                HttpSession session = (HttpSession) context.getExternalContext().getSession(true);
                session.setAttribute("loggedIn", new Object());
            }
        } else {
            message = new FacesMessage(FacesMessage.SEVERITY_WARN, "Login Error!", "Username oder Passwort falsch!");
            logger.log(Level.INFO, "logged in");
        }

        FacesContext.getCurrentInstance().addMessage(null, message);
        logger.log(Level.INFO, "logged in");

    }

    public Object logout() throws IOException {
        FacesContext context = FacesContext.getCurrentInstance();
        FacesMessage message;

        HttpSession session = (HttpSession) context.getExternalContext().getSession(true);
        session.removeAttribute("loggedIn");
        session.invalidate();

        message = new FacesMessage(FacesMessage.SEVERITY_INFO, username, " logged out!");

        context.getExternalContext().getFlash().setKeepMessages(true);

        //PrimeFaces.current().dialog().showMessageDynamic(message);
        FacesContext.getCurrentInstance().addMessage(null, message);
        logger.log(Level.INFO, "logged out");
        return "logout";
    }

    public void changePassword() throws IOException {
        FacesContext context = FacesContext.getCurrentInstance();
        FacesMessage message = null;

        Benutzer b = service.selectBenutzer(this.username);

        String salt = null;
        String providedPassword = null;
        String securePassword = null;

        if (b != null) {
            salt = b.getSalt();
            providedPassword = this.chechPw;
            securePassword = b.getPassword();
        }

        boolean passwordsMatch = PasswordUtils.verifyUserPassword(providedPassword, securePassword, salt);
        boolean newPasswordsMatch = true;
        boolean newPasswordOK = true;
        boolean newPasswordIsOldOne = false;

        if (!this.newPw.equals(this.newPw1)) {
            newPasswordsMatch = false;
            message = new FacesMessage(FacesMessage.SEVERITY_WARN, "Error!", "Passwörter stimmen nicht überein!");
        }

        if (this.newPw.length() < 5 || this.newPw.length() > 12 || !this.newPw.matches(".*\\d+.*")) {
            newPasswordOK = false;
            message = new FacesMessage(FacesMessage.SEVERITY_WARN, "Error!", "Das Passwort sollte "
                    + "5 bis 12 Zeichen lang sein und mindestens einen Nummer beinhalten.");
        }
        if (this.newPw.equals(this.chechPw)) {
            newPasswordIsOldOne = true;
            message = new FacesMessage(FacesMessage.SEVERITY_WARN, "Error!", "Neues Password sollte mit dem alten"
                    + "nicht übereinstimmen!");
        }

        if (passwordsMatch && newPasswordsMatch && newPasswordOK && !newPasswordIsOldOne) {
            String mySecurePassword = PasswordUtils.generateSecurePassword(this.newPw, salt);

            b.setPassword(mySecurePassword);
            service.updateBenutzer(b);
            message = new FacesMessage(FacesMessage.SEVERITY_INFO, "Success!", "Passwort erfolgreich geändert!"
                    + "Bitte melden Sie sich erneut an mit Ihrem neuen Passwort!");
            context.getExternalContext().redirect("/HTL_Plus_Informatik/faces/Login.xhtml");
            logout();
        } else if (!passwordsMatch && newPasswordsMatch && newPasswordOK && !newPasswordIsOldOne) {
            message = new FacesMessage(FacesMessage.SEVERITY_WARN, "Error!", "Altes Passwort ist falsch!");
        }

        context.getExternalContext().getFlash().setKeepMessages(true);
        FacesContext.getCurrentInstance().addMessage(null, message);
    }
}

web/Login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Login</title>
    </h:head>
    <h:body style="background-color: #F2F2F2;">
        
        <h:form id="menuForm" style="width: 100%;  background-color: #F2F2F2;">
            <h:graphicImage value="/resources/images/HTL-Pinkafeld_LOGO_WEB.svg" width="40%"/>
        </h:form>
        
        <div id="ueberschriftForm" align="center" style="margin-top: 10px;">
            <h:outputText value="Verein HTL Plus Informatik" style="font-size: 55px; color: #FFBF00;"/>
        </div>

	<h:form id="loginForm" >
		<p:growl id="msg" showDetail="true" life="4000" sticky="true"/>
		<p:panel id="loginPnl" header="Login" style="width: 350px; margin: 0 auto; margin-top: 30px;">
                     <p:focus context="loginPnl"/>
                    <h:panelGrid id="loginPanel" columns="2" cellpadding="5">
				<h:outputText value="Username" />
				<p:inputText id="username" value="#{loginBean.username}"></p:inputText>
				<p:spacer /><p:spacer />	
				<h:outputText value="Passwort" />
                                <p:password id="password" value="#{loginBean.password}"></p:password>
				<p:message for="password"></p:message>
			</h:panelGrid>
			<h:panelGrid columns="1" cellpadding="10" width="100%">
				<p:commandButton value="Login" update="msg" action="#{loginBean.login}" icon="fa fa-sign-in"/>
                        </h:panelGrid>
		</p:panel>
	</h:form>
    </h:body>
</html>

web/MitgliedStart.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Startseite Mitglied</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </h:head>
    <h:body style = "background-color: #F2F2F2">
        <h:form id="menuForm" style="width: 100%; ">
            <h:graphicImage value="/resources/images/HTL-Pinkafeld_LOGO_WEB.svg" width="40%"/>
        </h:form>
        
        <h:form>  
            <p:growl id="message" showDetail="true" life="4000" sticky="true"/>
 
            <p:menubar style="background-color: #FFBF00;">
                <p:menuitem url="/faces/MitgliedStart.xhtml" icon="fa fa-home"/>

                <p:menuitem value="Bildungspartner" url="/faces/RestrictedBildungspartner.xhtml"/>
 
                <p:menuitem value="Mitglieder" url="/faces/RestrictedMitglieder.xhtml"/>
 
                <f:facet name="options">
                    <p:commandButton value="Password ändern" action="#{passwordBean.restrictedChangePassword()}"/>
                    <p:commandButton value="#{loginBean.username} - Logout" update="messages" action="#{loginBean.logout}" icon="fa fa-sign-out"/>
                </f:facet>
            </p:menubar>
            <p:messages id="messages" showDetail="true" closable="true">
                <p:autoUpdate/>
            </p:messages>
        </h:form>
        
        <h:form id="mainForm" >
             <h:graphicImage value="/resources/images/Welcome.svg" width="30%" style="margin-left: 32%;"/>
        </h:form>
    </h:body>
</html>

web/RestrictedBildungspartner.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Bildungspartner verwalten</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <style type="text/css">

        </style>
    </h:head>
    <h:body style = "background-color: #F2F2F2">
        <h:form id="menuForm" style="width: 100%; ">
            <h:graphicImage value="/resources/images/HTL-Pinkafeld_LOGO_WEB.svg" width="40%"/>
        </h:form>
        
        <h:form>  
            <p:growl id="messages" showDetail="true" life="4000" sticky="true"/>
 
            <p:menubar style="background-color: #FFBF00;">
                <p:menuitem url="/faces/MitgliedStart.xhtml" icon="fa fa-home"/>

                <p:menuitem value="Bildungspartner" url="/faces/RestrictedBildungspartner.xhtml"/>
 
                <p:menuitem value="Mitglieder" url="/faces/RestrictedMitglieder.xhtml"/>
                
                <f:facet name="options">
                    <p:commandButton value="Password ändern" action="#{passwordBean.restrictedChangePassword()}"/>
                    <p:commandButton value="#{loginBean.username} - Logout" update="messages" action="#{loginBean.logout}" icon="fa fa-sign-out"/>
                </f:facet>
            </p:menubar>
        </h:form>
        
        <h:form id="mainForm">     
            <p:panel id="mainPanel" header="Bildungspartner verwalten" style="margin-top: 10px; position: relative; font-size: 15px;">
                <p:dataTable var="bildpa" value="#{htlPlusService.bpList}" filteredValue="#{htlPlusService.filteredBpList}" scrollable="true" style="font-size: 10px;" scrollHeight="400" scrollWidth="98%">
                            <f:facet name="header">
                                <p:outputPanel>
                                    <h:outputText value="Search all fields:" />
                                    <p:inputText id="globalFilter" onkeyup="PF('bpTable').filter()" style="width:150px" placeholder="Enter keyword"/>
                                </p:outputPanel>
                            </f:facet>
                    
                            <p:column headerText="ID" style="width: 25px;" sortBy="#{bildpa.id}">
                                <h:outputText value="#{bildpa.id}" />
                            </p:column>
                    
                            <p:column headerText="Firmenname" style="width: 80px;" sortBy="#{bildpa.firma}" filterMatchMode="contains">
                                <h:outputText value="#{bildpa.firma}" />
                            </p:column>
      
                            <p:column headerText="Adresse" style="width: 55px;" sortBy="#{bildpa.addr}" filterMatchMode="contains">
                                <h:outputText value="#{bildpa.addr}" />
                            </p:column>
 
                            <p:column headerText="PLZ" style="width: 35px;" sortBy="#{bildpa.plz}">
                                <h:outputText value="#{bildpa.plz}" />
                            </p:column>
                    
                            <p:column headerText="Ort" style="width: 30px;" sortBy="#{bildpa.ort}">
                                <h:outputText value="#{bildpa.ort}" />
                            </p:column>
 
                            <p:column headerText="Absolvent" style="width: 60px;" sortBy="#{bildpa.absolvent}">
                                <h:selectBooleanCheckbox disabled="true" value="#{bildpa.absolvent}" />
                            </p:column>
                    
                            <p:column headerText="Webseite" style="width: 80px;">
                                <h:outputText value="#{bildpa.website}" />
                            </p:column>
                    
                            <p:column headerText="Fax" style="width: 50px;">
                                <h:outputText value="#{bildpa.fax}" />
                            </p:column>
                    
                            <p:column headerText="Email" style="width: 130px;">
                                <h:outputText value="#{bildpa.email}" />
                            </p:column>
                    
                            <p:column headerText="Betrag" style="width: 50px;" sortBy="#{bildpa.betrag}">
                                <h:outputText value="#{bildpa.betrag}€" />
                            </p:column>
                    
                            <p:column headerText="Bezahlt" style="width: 55px;" sortBy="#{bildpa.bezahlt}">
                                <h:selectBooleanCheckbox disabled="true" value="#{bildpa.bezahlt}" />
                            </p:column>
                    
                            <p:column headerText="Eintrittsdatum" style="width: 80px;" sortBy="#{bildpa.eDatum}">
                                <h:outputText value="#{bildpa.eDatum}" />
                            </p:column>
                    
                            <p:column headerText="Austrittsdatum" style="width: 80px;" sortBy="#{bildpa.aDatum}">
                                <h:outputText value="#{bildpa.aDatum}" />
                            </p:column>
                    
                            <p:column headerText="Anmerkung" style="width: 60px;">
                                <h:outputText value="#{bildpa.anmerk}" />
                            </p:column>
                    
                </p:dataTable>
                
            </p:panel>
        </h:form>
  
    </h:body>
</html>

web/RestrictedChangePassword.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Login</title>
    </h:head>
    <h:body style="background-color: #F2F2F2;">
        
        <h:form id="menuForm" style="width: 100%;  background-color: #F2F2F2;">
            <h:graphicImage value="/resources/images/HTL-Pinkafeld_LOGO_WEB.svg" width="40%"/>
        </h:form>

	<h:form>
		<p:growl id="msg" showDetail="true" life="4000" sticky="true"/>
		<p:panel id="pwPnl" header="Passwort Ändern" style="width: 350px; margin: 0 auto; margin-top: 30px;">
                     <p:focus context="pwPnl"/>
                    <h:panelGrid id="pwPanel" columns="2" cellpadding="5">
				<h:outputText value="Altes Passwort eingeben:" />
                                <p:password id="passwordold" value="#{loginBean.chechPw}"/>
                                <h:outputText value="Neues Passwort eingeben:" />
                                <p:password id="passwordnew" value="#{loginBean.newPw}"/>
                                <h:outputText value="Neues Passwort wieder eingeben:" />
                                <p:password id="passwordnew1" value="#{loginBean.newPw1}"/>
			</h:panelGrid>
                     
			<h:panelGrid columns="2" width="100%">
				<p:commandButton value="Ändern" update="msg" action="#{loginBean.changePassword}" icon="fa fa-sign-in"/>
                                <p:commandButton value="Abbrechen" action="#{passwordBean.cancel()}"/>
                        </h:panelGrid>
		</p:panel>
	</h:form>
    </h:body>
</html>

web/RestrictedMitglieder.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Mitglieder verwalten</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <style type="text/css">

        </style>
    </h:head>
    <h:body style = "background-color: #F2F2F2">
        <h:form id="menuForm" style="width: 100%; ">
            <h:graphicImage value="/resources/images/HTL-Pinkafeld_LOGO_WEB.svg" width="40%"/>
        </h:form>
        
        <h:form>  
            <p:growl id="messages" showDetail="true" life="4000" sticky="true"/>
 
            <p:menubar style="background-color: #FFBF00;">
                <p:menuitem  url="/faces/MitgliedStart.xhtml" icon="fa fa-home"/>

                <p:menuitem value="Bildungspartner" url="/faces/RestrictedBildungspartner.xhtml"/>
 
                <p:menuitem value="Mitglieder" url="/faces/RestrictedMitglieder.xhtml"/>

                <f:facet name="options">
                    <p:commandButton value="Password ändern" action="#{passwordBean.restrictedChangePassword()}"/>
                    <p:commandButton value="#{loginBean.username} - Logout" update="messages" action="#{loginBean.logout}" icon="fa fa-sign-out"/>
                </f:facet>
            </p:menubar>
        </h:form>
        
        <h:form id="mainForm" style="margin-bottom: 10px;">     
            <p:panel id="mainPanel" header="Mitglieder verwalten" style="margin-top: 10px; font-size: 15px;" >
                <p:dataTable var="mitglied" value="#{htlPlusService.MList}" scrollable="true" style="font-size: 12px;" scrollHeight="400" scrollWidth="98%" >
                    <p:column headerText="ID" style="width: 10px;">
                        <h:outputText value="#{mitglied.id}" />
                    </p:column>
                    
                    <p:column headerText="Vorname" style="width: 60px;">
                        <h:outputText value="#{mitglied.vname}" />
                    </p:column>
                    
                    <p:column headerText="Nachname" style="width: 60px;">
                        <h:outputText value="#{mitglied.nname}" />
                    </p:column>
                    
                    <p:column headerText="Funktion" style="width: 80px;">
                        <h:outputText value="#{mitglied.funktion}" />
                    </p:column>
 
                    <p:column headerText="E-Mail" style="width: 80px;">
                        <h:outputText value="#{mitglied.email}" />
                    </p:column>
                    
                    <p:column headerText="Tel. Nr." style="width: 60px;">
                        <h:outputText value="#{mitglied.telnr}" />
                    </p:column>

                </p:dataTable>
                
            </p:panel>
        </h:form>
    </h:body>
</html>